
name: Metrics
on:
  # ตั้งเวลาอัปเดตอัตโนมัติทุกๆ เที่ยงคืน
  schedule:
    - cron: "0 0 * * *"
  # ให้กดสั่งรันเองในแท็บ Actions ได้
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # การตั้งค่าพื้นฐาน
          user: ctrlaltnate
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Bangkok
          
          # ตัวอย่าง Plugins (ปรับเลือกเปิด/ปิดตามชอบได้ครับ)
          plugin_lines: yes          # แสดงจำนวนบรรทัด code ที่เขียน
          plugin_isocalendar: yes     # แสดงกราฟ Commit แบบ 3D
          plugin_languages: yes       # แสดงภาษาคอมพิวเตอร์ที่ใช้บ่อย