name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # ----------------------------------------------------
      # การ์ดที่ 1: ส่วนการ์ดหลัก + Languages + Isometric (Classic Template)
      # ----------------------------------------------------
      - name: Main Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics-main.svg # ชื่อไฟล์แยกที่ 1
          
          user: ctrlaltnate
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Bangkok

          # Isometric Commit Calendar (Full year)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # Languages
          plugin_languages: yes

      # ----------------------------------------------------
      # การ์ดที่ 2: ส่วน Starred Topics (Terminal Template)
      # ----------------------------------------------------
      - name: Terminal Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics-terminal.svg # ชื่อไฟล์แยกที่ 2
          
          user: ctrlaltnate
          template: terminal
          base: "" # ปิดข้อมูลพื้นฐานออก ให้แสดงแค่ Topics ในสไตล์ Terminal
          config_timezone: Asia/Bangkok

          # Isometric Commit Calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # Starred topics
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: starred